fixtures:
  forge_modules:
    augeasproviders: "herculesteam-augeasproviders"
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib"
    concat: "https://github.com/puppetlabs/puppetlabs-concat"
    limits: "https://github.com/erwbgy/puppet-limits"
    cron_core:
      repo: https://github.com/puppetlabs/puppetlabs-cron_core.git
      puppet_version: ">= 6.0.0"
